### PR TITLE
Korean checking (한국어 검수)

### PR DESCRIPTION
**Pull request by 64KB-Games**
#### About pull request
- To get more insight, please check the related issue #177.

#### What's changed to accomplish [problem / feature] described in issue

Coding rule check is done [yes]

### CODE REVIEW

**Comment by MrGreensWorkshop** [comment]
Hi, Thank you for checking out and fixing the translations. Before merging this, the branch needs to be updated because French has been added. I will do it as soon as I can.
Thank you for your time and effort.

**Comment by MrGreensWorkshop** [comment]
@64KB-Games Hi, I check the fixes, Thank you. There is one thing that I want to mention.

There is translation that tells how long post it is. something like this "3 minutes read."

With you current suggestion, it is looks like this. "3분 전 읽음"

```
post:
  read_time:
    unit: "분 전"
    text: " 읽음"
 ```
 
I searched for how other blogs write, and it mostly looks like this. "3분 읽기"
 
Screenshot 2023-05-07 at 18 32 31

```
post:
  read_time:
    unit: "분"
    text: " 읽기"
 ```
 
 What do you think?

**Comment by 64KB-Games** [comment]
i understand "3 min before someone reads

in korean "3분 전에 읽음" or "3분 전 읽음"
 
but it means reading time

post:
  read_time:
    unit: "분간"
    text: " 읽음"

and I removed my fork. Am I wrong?

**Comment by MrGreensWorkshop** [comment]
@64KB-Games  Hi, I think you misunderstand me. I didn't ask you to close the pull request or reject your fixes. I was so happy about the fixes except one.

"3 min read" is not equal to "3 min before someone reads."
That's why I checked how other Korean blogs express it, so what I found was "3분 읽기".

you can check these pages.
https://www.neeyamo.com/ko/blog/guggyeong-gan-geubyeo-gwanliui-bogjabseong-ihae
https://datadoctorblog.com/categories/Blog/
https://www.tandem.net/ko/blog/category/tandem-tales
https://linkmix.co.kr/s/blog/C2QZJ5AOu
https://kinetic.moe/

I want this translation to be as common as other Korean blogs, which is why I wanted to improve the translation and asked for your opinion. That's all.

You are welcome to reopen the pull request if you wish to.
Thanks anyway.

**Pull request closed without merging**
