### PR TITLE
Date month is not translated in non english pages.

### PR DESCRIPTION
**Pull request by MrGreensWorkshop**
#### About pull request
- To get more insight, please check the related issue #119 

#### What's changed to accomplish [problem / feature] described in issue
- get-localized-long-date-format.liquid created to replace %b with month list items.
- now on, effected pages gets format from this.
- comment about date added to _data/lang/[lang].yml

Coding rule check is done [yes]

### CODE REVIEW

**Review by MrGreensWorkshop — COMMENTED** [review]
all effected pages checked locally

**Review by MrGreensWorkshop — COMMENTED** [review]
before and after changes _site output is same. This fix will not effect anyone.

**Comment by MrGreensWorkshop** [comment]
@fandangos Could you please check it?
I had to add some content. how does it look?
https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com/pt/

**Comment by fandangos** [comment]
I would change `multilíngue` to `multi idiomas` or would change like this:

`[Mr. Green](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme) é um tema com suporte a vários idiomas gerado com [Jekyll](https://jekyllrb.com/) e totalmente compatível com [GitHub Pages](https://pages.github.com/).`

Multilingue isn't common in brazilian portuguese and the proposed translation is much read friendly for portuguese speakers.

The rest looks amazing and works great, fantastic work!

**Comment by MrGreensWorkshop** [comment]
OK, done. Thank you for your contribution!

**Pull request merged**
